# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.

os: linux
dist: bionic

script:
  - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
  - bash merge_if_success.sh | tee merge.log

after_failure:
  - cat merge.log

notifications:
    slack:
      secure: "ldqBRgSPbNYCxEz+JaBq85jQotTM2V6YK9igQ4lG/lgKD4eCKg/mxNdetNWc4Fr+WkYnK5il/rjcAmOSVk2CndE5VmqrVCe195WBtgHRH+8PO08YIZNz+NzH7Q5V53+h9wBrywCpTIeOzZ1k/D1WW6kLwP4fHUVhsejntsa9l1pPEGmiD3HbVdtpRynbqN1NifKpAAo/EC5KF8EKmu5EDEOdhb/cbijIeFWxYGslMB9BkiQpg9edZksj7tyqIKaupIO81XG0VwW/giq/ZDFknytNVGGugGmCYYKRBoyfQNbOYiq9wZ0T2LpvIAQrpFqdvQ/36fsUVO6QiSWE7GQN5/VneUGmocGGG3RQ/OBVgjSGBn0XdetN6dl/C2Ma66bURitvzOVBu9cRVoEMmC7tfc/uo9hsxNT/ZrTwcw3O2uKMRWKHT47l+Pz2fE11J97IzEzm4XGFblY/dsSHe30X2M1Z+/9gCc/Oz5ZegeInQZfCpoEx0wdhYBDa/qd3TKLx1EeCeHS2f6RCQf6yZyTuU9uJB2/tD55rge/ilTfhZ1Z6qBacc4zoxRSwoQae08YV29ikHMWlOqmicVyFr76+uz+wqtMizei3Bvh/mfeIT5ewGrNom7u2yQsHI1CkH99fGIMDTYXzk0PZ+842wR3CAHs9h7h4Mp66M6wJ5+gcGMM="

env:
  global:
    # SLACK_TOKEN, build-bot
    - secure: "Hp8X60/DdvyxZtb8RbwwLnILo4QNbeqg8Vkq1jNEEStvKbCYGKfltzWW1im1LcG5rE4KvkvmXRas20jUPqnZ22Q2ld117rCn6cBHyzuurBhb7UUpo9yroLR1jvInrRPe9RWPg21xbBB8aIrzWspMxGU/ZTD6EQG9LXU6PAvBYS2M1RcH1pPt4Roruo/RlrH4g2TmYfBUvi4RVWJ7ONY4mi2fqQy10Lv2KKZF6cezXCtFn9CJYWOkw2DFW9ZibMYjIEocHfk29SiloSt+fF5Eb7jrw3Qqvn3RgjdYKSHQu3KN59xEbVmShUqT3KEt8n6Aw48ZZW57ePPMWBDJ2Qmp33jaJHve6+sWJQfSeY135R269tSGF1xXza+4u4pJkmzNRsrQW6OywkzEQCuZVew+2zGX3BXiFov8dp8wNZmz5tGthAyq0xJsim+LdpT/GSINytc4fBx/JDnWRSS4RBrSHNS16aSIHvZ1YeX/tV+gAXt6dCAl7AnTQCjJ2l1ncadi+rWWNH5y3vrtELlxnFGF3W4UL3pP70Dt3HqoRYkCBLAvj6kIMk3dnvun5wXvaN7RMc4kWk5DJJNnx9cDgqMjkTm36S3XCerF5MzU/arlxO9Kii3gEAZWV8arUbRpToxkP7d1rasw3KcgeFwoMBP5Jcm55tWGMfoCGbmaIajC3vo="

    # GITHUB_TOKEN
    - secure: "iZOyOz5xCadu4GTuB4Y0YWVUoYS5xHIxoQ+nj1M6ecfDXLIMmonkyFn+YOd9itasTIBPZNupCdCrwbg5zmd3KEfOoGVxM4Imielmf6x/OHw49PZbkx9m9YxI0/hjopnZ88NvWPrlfk3rtfNm2CbA/cNKH9TXwge3OnhrZQs8NdHDmPfNhlsWNMFm1a7ivuRr5scaI4pj2F1LD6aeEWr/cReS5fwPtIc4aS/x9OP6hN+0rlVSlec3LJ2N9OsuWwVMyjclJsEyWf6JxCwRnYnOQZHiCVI+aAzkDraoZdRT5aGVpAmscr5wCkduQxSp2UUs9VKzpekqXdP7HIfvygFWr79tt7uiBI2V1I+L97wJU+t2rCJTviBTb+F26ukx26VkU40hcclQuFIzGl1YkgiuM0KdPt1dTYOELLXYbtBhkUrP7nITRGxwEw9RjwYkCuJFy9HybqQjXvjjn53ki/3Zdpeud7BS/PDKNzN/PuGypPvtF4T6bUkSbJ14qz7jTfziWQ6GvnbU609Qf+gSGFVW7gEdhXAq2NyfYVfKwS0QXMJBUHNH11wE4+/kODuxrohdF+eNe00woNehJ+HaO2MsqEoiblbZ0WmZM7Qcx1NtJ8rteAglaCML9pIeqv6mrOOVCPvJNF6Qjtem0PXUlbdJzOSqwYedhPjhA886jdZ0Tzw="

    # TRAVIS_COMMIT_TOKEN
    - secure: "Lfx7e72LSt2XExhJ5AByxEWvgXcWM/5seClEVNvkpq4SzIoBZPUrdokZm4qG6/fjZrhXYh2HUKkg7MN5/HFSvHMllpH0oTpy0wqFX9WsuZ0CN2H3v4tudlfsotvkEWZ+ywl4Woc5jx6iYCQqpL4ouxICrLWtdEiK152AQCWmks7siFGjon78s9gX1vVARFP7YRIAt99CY5UmiK8+fJBvtEW8CJU83fQQidYM55ejiFD3qOgM3LW9mM55W/xkkaz45vNuPkm5I5vDpah50xpyvMAF1EAVUPPEa4ihDMinAg0jNbAqqkOY3x053lK78DBoJbqU0wWCSFkgfvEUZv4wonaXapX8Sgcn/6umpvBJbO+14/m38QEGAGbGhjAKdoeEm90BYi7HTnHlQKw76BTeWpUSHc/QEsJmUrOdmnSAPYgPOBNhg5ZD9X3jtxfqzIz30KsZ6MuYOcM09hwsh3c12UCc2Rg+jwlxBLm4rEQzSc5wiw/YVRxIwxxNAIK8ywQuyp2eDAGSt/gqZk0K/YgeygeVJq/NWjaPgKN6ckKEeXPf4fOSNX4WDx2uoEsvnGdzVz8WOBqVo4MDJ3xOI0G4Xu+N9sdsAiGj4ubMalhaMrLbEvMr3hPizP8GBD864qtbKd9xp0SK3IqwXNxRTy3+xk/uSV9LwMMZvhcTat6f9sc="

    # TRAVIS_AUTH_TOKEN
    - secure: "XIlY24qCpRDLDaE4vylsmYPZMdOjvIhXeyl4izekiuo2Q1WshMD6rLhNMMyE3kI5rFYjvzMlNZazjDdXXWz+SQpAkhil7vi8xOfDsIgnMGIHSpkHR5ZSji4pJ6RdZ+N3f2V8YSYtAeJnieyDhT9OqNB2AZOF2gC5ZEgrBwStOP8bneQYW/H9ZPQUSCZo2JOLJWvjDAvIFQ7yxeMkCNAIbySWAxbC077UPXtpZhlGxbAwuVfxYWBaPPuPN/t7aSMQ2lCZHQFhST4CMBoUyN+Zul/0e662E836wD7/tEuxxgcHgGALS6H28OzP6PjIR2Rebn19kdXBx8DphlEdsChtf4Bzm3pLJMDFUYh413ca3Y7S4hXbgZJUFqQP2VmhYYvGXXD1bVtCcrK0Z1PgAKcviAboaBAuQUiAqW/tNj653d5g6oWHED7cipe4v4xD8/uSnkrTvnThZ9UxViZPEOJ+KV1/qpmYEoNIFWpsSgKj4WZu0bVarRWubCzFdiEZxky+unoku3nCzqjLL/8i+0T0mFRnShwKYKwAjrEcpOIq2Zz20fLW+SeAEX/uOVzbFSRQLSLo1ClHrmz7mzN/HJ+Qv1FifOGOxFPblwOugKV/0ksrN6aDE43BgXCwiDFKRXO2pQsxJ7OggsEip2/kg8HecPjzg5h64JxRe5W5QOwMTA4="
